[package]
name = "rust-melspec-wasm"
version = "0.1.0-alpha.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
num = "^0.4"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.5"
